/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ajustes.Vista;

/**
 *
 * @author Oku
 */
public class Preferencias_Entorno_Inicio extends javax.swing.JPanel
{

    /**
     * Creates new form Preferencias_Entorno_Inicio
     */
    public Preferencias_Entorno_Inicio()
    {
        initComponents();
        //((javax.swing.JSpinner.DefaultEditor)downloadEvery.getEditor()).getTextField().setEditable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        webcfg = new javax.swing.JPanel();
        downloadEvery = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setMaximumSize(new java.awt.Dimension(330, 226));
        setMinimumSize(new java.awt.Dimension(330, 226));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(330, 226));
        setLayout(null);

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mostrar página de inicio", "Mostrar registro de nuevo profesor", "Mostrar registro de nuevo horario", "Mostrar gestor de consultas", "Mostrar página web de secretaria unefa lara" }));
        jComboBox1.setOpaque(false);
        add(jComboBox1);
        jComboBox1.setBounds(10, 39, 320, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Al iniciar:");
        add(jLabel1);
        jLabel1.setBounds(10, 19, 70, 14);

        webcfg.setOpaque(false);

        downloadEvery.setModel(new javax.swing.SpinnerNumberModel(10, 10, 60, 10));
        downloadEvery.setDoubleBuffered(true);
        downloadEvery.setEditor(new javax.swing.JSpinner.NumberEditor(downloadEvery, ""));
        downloadEvery.setOpaque(false);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("minutos");

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Actualizar página cada:");
        jCheckBox1.setOpaque(false);

        javax.swing.GroupLayout webcfgLayout = new javax.swing.GroupLayout(webcfg);
        webcfg.setLayout(webcfgLayout);
        webcfgLayout.setHorizontalGroup(
            webcfgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webcfgLayout.createSequentialGroup()
                .addGroup(webcfgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addGroup(webcfgLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(downloadEvery, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        webcfgLayout.setVerticalGroup(
            webcfgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(webcfgLayout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(webcfgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(downloadEvery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(webcfg);
        webcfg.setBounds(10, 77, 148, 56);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner downloadEvery;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel webcfg;
    // End of variables declaration//GEN-END:variables
}
